### YamlMime:ManagedReference
items:
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig
  commentId: T:ASE_SABIN_KHANAL_77358588.GlobalConfig
  id: GlobalConfig
  parent: ASE_SABIN_KHANAL_77358588
  children:
  - ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
  - ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  - ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  - ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
  langs:
  - csharp
  - vb
  name: GlobalConfig
  nameWithType: GlobalConfig
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig
  type: Class
  source:
    remote:
      path: ASE_SABIN_KHANAL_77358588/ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-ksabin22.git
    id: GlobalConfig
    path: ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
    startLine: 11
  assemblies:
  - ASE_SABIN_KHANAL_77358588
  namespace: ASE_SABIN_KHANAL_77358588
  summary: Holds global configuration settings for the application.
  example: []
  syntax:
    content: public class GlobalConfig
    content.vb: Public Class GlobalConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
  id: IsFillEnabled
  parent: ASE_SABIN_KHANAL_77358588.GlobalConfig
  langs:
  - csharp
  - vb
  name: IsFillEnabled
  nameWithType: GlobalConfig.IsFillEnabled
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
  type: Property
  source:
    remote:
      path: ASE_SABIN_KHANAL_77358588/ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-ksabin22.git
    id: IsFillEnabled
    path: ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
    startLine: 20
  assemblies:
  - ASE_SABIN_KHANAL_77358588
  namespace: ASE_SABIN_KHANAL_77358588
  summary: Gets or sets the filled status, which determines whether shapes should be filled or not.
  example: []
  syntax:
    content: public static bool IsFillEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
      description: >-
        A boolean value indicating the filled status. 

        The default value is <code>false</code>.
    content.vb: Public Shared Property IsFillEnabled As Boolean
  overload: ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled*
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  id: MaxX
  parent: ASE_SABIN_KHANAL_77358588.GlobalConfig
  langs:
  - csharp
  - vb
  name: MaxX
  nameWithType: GlobalConfig.MaxX
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  type: Property
  source:
    remote:
      path: ASE_SABIN_KHANAL_77358588/ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-ksabin22.git
    id: MaxX
    path: ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
    startLine: 31
  assemblies:
  - ASE_SABIN_KHANAL_77358588
  namespace: ASE_SABIN_KHANAL_77358588
  summary: >-
    Gets or sets the maximum X coordinate (width) of the canvas.

    This value defines the maximum horizontal position during drawing operations.

    The default value is 640 pixels.
  remarks: >-
    The value of <xref href="ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX" data-throw-if-not-resolved="false"></xref> should be updated if you want to change the canvas's horizontal limit.

    It should be a positive integer value.
  example: []
  syntax:
    content: public static int MaxX { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxX As Integer
  overload: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX*
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  id: MaxY
  parent: ASE_SABIN_KHANAL_77358588.GlobalConfig
  langs:
  - csharp
  - vb
  name: MaxY
  nameWithType: GlobalConfig.MaxY
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  type: Property
  source:
    remote:
      path: ASE_SABIN_KHANAL_77358588/ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-ksabin22.git
    id: MaxY
    path: ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
    startLine: 42
  assemblies:
  - ASE_SABIN_KHANAL_77358588
  namespace: ASE_SABIN_KHANAL_77358588
  summary: >-
    Gets or sets the maximum Y coordinate (height) of the canvas.

    This value defines the maximum vertical position during drawing operations.

    The default value is 480 pixels.
  remarks: >-
    The value of <xref href="ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY" data-throw-if-not-resolved="false"></xref> should be updated if you want to change the canvas's vertical limit.

    It should be a positive integer value.
  example: []
  syntax:
    content: public static int MaxY { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxY As Integer
  overload: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY*
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
  id: PenSize
  parent: ASE_SABIN_KHANAL_77358588.GlobalConfig
  langs:
  - csharp
  - vb
  name: PenSize
  nameWithType: GlobalConfig.PenSize
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
  type: Property
  source:
    remote:
      path: ASE_SABIN_KHANAL_77358588/ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-ksabin22.git
    id: PenSize
    path: ASE_SABIN_KHANAL_77358588/GlobalConfig.cs
    startLine: 55
  assemblies:
  - ASE_SABIN_KHANAL_77358588
  namespace: ASE_SABIN_KHANAL_77358588
  summary: Gets or sets the global pen size used in drawing operations.
  remarks: >-
    The pen size determines the thickness of lines in drawing operations.

    A value of 1 indicates a pen thickness of 1 pixel, and the default value is 1.
  example: []
  syntax:
    content: public static int PenSize { get; set; }
    parameters: []
    return:
      type: System.Int32
      description: >-
        An integer representing the pen size. Determines the thickness of lines in drawing operations.

        The default value is <code>1</code>.
    content.vb: Public Shared Property PenSize As Integer
  overload: ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize*
references:
- uid: ASE_SABIN_KHANAL_77358588
  commentId: N:ASE_SABIN_KHANAL_77358588
  href: ASE_SABIN_KHANAL_77358588.html
  name: ASE_SABIN_KHANAL_77358588
  nameWithType: ASE_SABIN_KHANAL_77358588
  fullName: ASE_SABIN_KHANAL_77358588
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled*
  commentId: Overload:ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_IsFillEnabled
  name: IsFillEnabled
  nameWithType: GlobalConfig.IsFillEnabled
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.IsFillEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_MaxX
  name: MaxX
  nameWithType: GlobalConfig.MaxX
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX*
  commentId: Overload:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_MaxX
  name: MaxX
  nameWithType: GlobalConfig.MaxX
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxX
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  commentId: P:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_MaxY
  name: MaxY
  nameWithType: GlobalConfig.MaxY
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY*
  commentId: Overload:ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_MaxY
  name: MaxY
  nameWithType: GlobalConfig.MaxY
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.MaxY
- uid: ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize*
  commentId: Overload:ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
  href: ASE_SABIN_KHANAL_77358588.GlobalConfig.html#ASE_SABIN_KHANAL_77358588_GlobalConfig_PenSize
  name: PenSize
  nameWithType: GlobalConfig.PenSize
  fullName: ASE_SABIN_KHANAL_77358588.GlobalConfig.PenSize
